import React from 'react'
import './Tutorial.css'
import { useNavigate } from 'react-router-dom';
import { IoMdCheckboxOutline } from "react-icons/io";

function Tutorial() {
    const navigateTo = useNavigate();
    const handleClickToAccount = () => {
        navigateTo('/account');
    };
    
  return (
    <div className='tutorial-container'>
        {/* <img/> */}
        <div className='tutorial-book-cover-container'>
            <div className='tutorial-book-outer-container'>
                <div className='tutorial-book-inner-container'>
                    <div className='tutorial-book-page-left-container'>
                        <div className='tutorial-page-padding'>
                            <div className=''>Welcome to your new To-Do List experience! Let's explore the features designed to enhance your productivity and organization</div>
                        </div>
                    </div>
                    <div className='tutorial-book-page-right-container'>
                        <div className='tutorial-page-padding'>
                            <div className='tutorial-book-listing-container'>
                                <div className='tutorial-book-listing-items'>
                                    <IoMdCheckboxOutline className='tutorial-book-listing-icon'/>
                                    <div className='tutorial-book-listing-description'>Google Calendar Integration: Seamlessly sync your Google Calendar with our to-do list. Complete tasks with a single click and watch them automatically disappear from your list.</div>
                                </div>
                                <div className='tutorial-book-listing-items'>
                                    <IoMdCheckboxOutline className='tutorial-book-listing-icon'/>
                                    <div className='tutorial-book-listing-description'>GPT-Optimized Schedules: Utilize schedules generated by AI to optimize your day. Let our advanced algorithms suggest the best way to allocate your time.</div>
                                </div>
                                <div className='tutorial-book-listing-items'>
                                    <IoMdCheckboxOutline className='tutorial-book-listing-icon'/>
                                    <div className='tutorial-book-listing-description'>AI-Powered Scheduling Advice: Stuck on planning your day? Ask GPT for expert advice on how to efficiently schedule your tasks.</div>
                                </div>
                                <div className='tutorial-book-listing-items'>
                                    <IoMdCheckboxOutline className='tutorial-book-listing-icon'/>
                                    <div className='tutorial-book-listing-description'>Track Your Tasks: Easily monitor tasks that need attention today and those upcoming. Stay organized and on top of your responsibilities.</div>
                                </div>
                                <div className='tutorial-book-listing-items'>
                                    <IoMdCheckboxOutline className='tutorial-book-listing-icon'/>
                                    <div className='tutorial-book-listing-description'>Progress Visualization: Watch your progress in real-time with our dynamic progress bar. Feel a sense of accomplishment as you complete tasks and see your progress visually.</div>
                                </div>
                            </div>
                            <div>Enjoy managing your tasks more effectively with these features!</div>
                            <button onClick={handleClickToAccount} className='tutorial-book-button' aria-label="Go to account settings">
                                OK
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  )
}

export default Tutorial